### ISSUE TITLE
Import flights (openflights CSV) not working

### ISSUE THREAD

**Issue by benmacd80** [jpatokal/openflights#1107]
I had a previous issue with flights not listing, so I backed up (exported) my entire data to CSV, and deleted all the data. Then when I go to reimport the flights again, I get an 'upload failed' error. I have tried editing the CSV to include only 1 flight and import that, and I get the same error.

**Comment by kurde78** [comment]
Same here, sample file created from empty backup and filled with sample data provided as example on CSV Format Specification page fails every time

**Comment by jpatokal** [comment]
Sorry, permissions error on the new server, this is now fixed.

**Comment by kurde78** [comment]
Uploading the file works now, but importing still does not. When I try with the sample 5 entries .csv from your CSV Format Spec example, I only get info about parsing and the first line displayed. No button to confirm, flights not imported... 

OpenFlights: Import
Upload successful. Parsing...

Results
Tmpfile phpbYrftn
ID	Date	Flight	From	To	Miles	Time	Plane	Reg	Seat	Class	Type	Reason	Trip	Comment
1	2008-01-18	10:30:10	ID 4533 SV559	ID 2188	ID 2082	542	01:35	ID 3	HZ-AKH	40C Aisle	Economy		Business	16	First, to Saudi!
